defmodule CelestialProtocol.Encoder.Society do
  import CelestialProtocol.Encoder.Helpers

  def encode_reputation(:stupid_minded), do: encode_int(-6)
  def encode_reputation(:useless), do: encode_int(-5)
  def encode_reputation(:not_qualified_for), do: encode_int(-4)
  def encode_reputation(:bluffed_name_only), do: encode_int(-3)
  def encode_reputation(:suspected), do: encode_int(-2)
  def encode_reputation(:neutral), do: encode_int(-1)
  def encode_reputation(:beginner), do: encode_int(1)
  def encode_reputation(:trainee_g), do: encode_int(4)
  def encode_reputation(:trainee_b), do: encode_int(5)
  def encode_reputation(:trainee_r), do: encode_int(6)
  def encode_reputation(:the_experienced_g), do: encode_int(7)
  def encode_reputation(:the_experienced_b), do: encode_int(8)
  def encode_reputation(:the_experienced_r), do: encode_int(9)
  def encode_reputation(:battle_soldier_g), do: encode_int(10)
  def encode_reputation(:battle_soldier_b), do: encode_int(11)
  def encode_reputation(:battle_soldier_r), do: encode_int(12)
  def encode_reputation(:expert_g), do: encode_int(13)
  def encode_reputation(:expert_b), do: encode_int(14)
  def encode_reputation(:expert_r), do: encode_int(15)
  def encode_reputation(:leader_g), do: encode_int(16)
  def encode_reputation(:leader_b), do: encode_int(17)
  def encode_reputation(:leader_r), do: encode_int(18)
  def encode_reputation(:master_g), do: encode_int(19)
  def encode_reputation(:master_b), do: encode_int(20)
  def encode_reputation(:master_r), do: encode_int(21)
  def encode_reputation(:nos_g), do: encode_int(22)
  def encode_reputation(:nos_b), do: encode_int(23)
  def encode_reputation(:nos_r), do: encode_int(24)
  def encode_reputation(:elite_g), do: encode_int(25)
  def encode_reputation(:elite_b), do: encode_int(26)
  def encode_reputation(:elite_r), do: encode_int(27)
  def encode_reputation(:legend_g), do: encode_int(28)
  def encode_reputation(:legend_b), do: encode_int(29)
  def encode_reputation(:ancien_hero), do: encode_int(30)
  def encode_reputation(:mysterious_hero), do: encode_int(31)
  def encode_reputation(:legendary_hero), do: encode_int(32)

  def encode_dignity(:neutral), do: encode_int(1)
  def encode_dignity(:suspected), do: encode_int(2)
  def encode_dignity(:bluffed_name_only), do: encode_int(3)
  def encode_dignity(:not_qualified_for), do: encode_int(4)
  def encode_dignity(:useless), do: encode_int(5)
  def encode_dignity(:stupid_minded), do: encode_int(6)

  def encode_faction(:neutral), do: encode_int(0)
  def encode_faction(:angel), do: encode_int(1)
  def encode_faction(:demon), do: encode_int(2)
end
